### ISSUE TITLE
update object storage & bandwidth with an input field

### ISSUE THREAD

**Issue by chrislittle** [CenturyLinkCloud/PriceEstimator#16]
please permit a direct quantity input field for Object Storage & bandwidth vs only the slider.  CTS sellers have filed a request for this as on certain browsers its hard to get the number exactly right.  a free form field is better for these 2 services.

**Comment by rpdubose** [comment]
@jim-phillips can you take a look at this one.  Apparently the slider's limit of 10TB is causing a lot of confusion w/ sales teams.  Can you replace the slider w/ a free form text input?

**Comment by rpdubose** [comment]
@chrislittle FYI.

We'll talk in the AM about when this goes out.  Likely early next wk but perhaps earlier.  We have some GA activities going on at the moment.

**Comment by srveit** [comment]
@chrislittle This is in production now.
