### ISSUE TITLE
object storage max

### ISSUE THREAD

**Issue by chrislittle** [CenturyLinkCloud/PriceEstimator#29]
https://www.ctl.io/estimator/

for some reason you can only choose 10TB of object storage on the estimator.  customers and sellers are inferring that is the max a customer can buy.  please fix this.

**Comment by rpdubose** [comment]
@chrislittle we're going to close this one in favor of #16.  Since it's a slider there has to be an upper limit but we're going to replace that w/ a text input to resolve the confusion.
