### ISSUE TITLE
Selecting GDP currency displays YEN currency symbol

### ISSUE THREAD

**Issue by markdaviesctl** [CenturyLinkCloud/PriceEstimator#3]
when using the Pricing Estimator at CenturyLinkCloud.com and selecting "GBP" as the currency, an error occurs and the actual currency symbol shows up as YEN
![screen shot 2015-05-08 at 10 27 43 am](https://cloud.githubusercontent.com/assets/11357775/7541827/e6b08bee-f56c-11e4-861b-7e35d291b331.png)

**Comment by dmak78** [comment]
This fix must happen in PublicPlatform. Fixing there.
